version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: secs-repo
    restart: always
    working_dir: /var/www/
    volumes:
      - .:/var/www
  nginx:
    image: nginx:1.29
    container_name: secs-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - .:/etc/nginx/conf.d
